name: Whale Alert Bot v5.3

on:
  workflow_dispatch:        # manual or immediate trigger
  schedule:
    - cron: '*/5 * * * *'  # automatic every 5 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Whale Bot with Telegram Logging
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.CHAT_ID }}
          MIN_USD: ${{ secrets.MIN_USD }}
        run: |
          source venv/bin/activate
          TIMESTAMP=$(date)
          echo "Running Whale Bot at $TIMESTAMP"

          for ATTEMPT in 1 2 3; do
            echo "Attempt $ATTEMPT..."
            python whale_bot.py
            STATUS=$?
            if [ $STATUS -eq 0 ]; then
              python - <<EOF
import os, requests
token = os.getenv('TELEGRAM_BOT_TOKEN')
chat_id = os.getenv('TELEGRAM_CHAT_ID')
message = f"✅ Whale Bot v5.3 succeeded on attempt {ATTEMPT} at {TIMESTAMP}"
requests.post(f"https://api.telegram.org/bot{token}/sendMessage", data={"chat_id": chat_id, "text": message})
EOF
              break
            else
              echo "Attempt $ATTEMPT failed."
              python - <<EOF
import os, requests
token = os.getenv('TELEGRAM_BOT_TOKEN')
chat_id = os.getenv('TELEGRAM_CHAT_ID')
message = f"⚠ Whale Bot v5.3 failed on attempt {ATTEMPT} at {TIMESTAMP}"
requests.post(f"https://api.telegram.org/bot{token}/sendMessage", data={"chat_id": chat_id, "text": message})
EOF
            fi
          done
